package cau4;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class Cau4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cau4.class.getName());

    /**
     * Creates new form hello
     */
    private DSSach danhSach = new DSSach();
    
    public Cau4() {
        initComponents();
        try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.FileInputStream("sach.dat"))) {
        danhSach.setDs((java.util.ArrayList<Sach>) ois.readObject());
        loadTable(); 
    } catch (Exception e) {
        // File chưa tồn tại hoặc rỗng, bỏ qua
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLbTenSach = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbMaSach = new javax.swing.JLabel();
        jLbTG = new javax.swing.JLabel();
        jLbNXB = new javax.swing.JLabel();
        jLbGia = new javax.swing.JLabel();
        jTextGia = new javax.swing.JTextField();
        jTextMaSach = new javax.swing.JTextField();
        jTextTenSach = new javax.swing.JTextField();
        jTextTG = new javax.swing.JTextField();
        jTextNXB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKQ = new javax.swing.JTable();
        jBtnThem = new javax.swing.JButton();
        jBtnXoa = new javax.swing.JButton();
        jBtnSua = new javax.swing.JButton();
        jBtnLuu = new javax.swing.JButton();
        jBtnTim = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnThoat = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbTenSach.setText("Tên Sách");

        jLabel2.setText("Thông tin sách");

        jLbMaSach.setText("Mã Sách");

        jLbTG.setText("Tác Giả");

        jLbNXB.setText("Nhà Xuất bản ");

        jLbGia.setText("Giá");

        jTextGia.addActionListener(this::jTextGiaActionPerformed);

        jTextMaSach.addActionListener(this::jTextMaSachActionPerformed);

        jTableKQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách ", "Tác giả", "NXB", "Giá"
            }
        ));
        jTableKQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKQMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKQ);

        jBtnThem.setText("Thêm");
        jBtnThem.addActionListener(this::jBtnThemActionPerformed);

        jBtnXoa.setText("Xóa");
        jBtnXoa.addActionListener(this::jBtnXoaActionPerformed);

        jBtnSua.setText("sửa");
        jBtnSua.addActionListener(this::jBtnSuaActionPerformed);

        jBtnLuu.setText("lưu");
        jBtnLuu.setActionCommand("lưu");
        jBtnLuu.addActionListener(this::jBtnLuuActionPerformed);

        jBtnTim.setText("tìm");
        jBtnTim.addActionListener(this::jBtnTimActionPerformed);

        jBtnClear.setText("clear");
        jBtnClear.addActionListener(this::jBtnClearActionPerformed);

        jBtnThoat.setText("thoát");
        jBtnThoat.addActionListener(this::jBtnThoatActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(367, 367, 367)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLbTG, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextTG, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jBtnThem)
                        .addGap(50, 50, 50)
                        .addComponent(jBtnXoa)
                        .addGap(33, 33, 33)
                        .addComponent(jBtnSua)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnLuu)
                        .addGap(38, 38, 38)
                        .addComponent(jBtnTim)
                        .addGap(41, 41, 41)
                        .addComponent(jBtnClear)
                        .addGap(43, 43, 43)
                        .addComponent(jBtnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbTG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnThem)
                    .addComponent(jBtnXoa)
                    .addComponent(jBtnSua)
                    .addComponent(jBtnLuu)
                    .addComponent(jBtnTim)
                    .addComponent(jBtnClear)
                    .addComponent(jBtnThoat))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGiaActionPerformed

    private void jBtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemActionPerformed
        try {
        String ma = jTextMaSach.getText();
        String ten = jTextTenSach.getText();
        String tg = jTextTG.getText();
        String nxb = jTextNXB.getText();
        double gia = Double.parseDouble(jTextGia.getText());

        if (ma.isEmpty() || ten.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thông tin không được để trống!");
            return;
        }

        Sach s = new Sach(ma, ten, tg, nxb, gia);
        if (danhSach.themSach(s)) {
            loadTable(); // Tự động làm mới bảng
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã sách bị trùng!");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Giá phải là số!");
    }
    }//GEN-LAST:event_jBtnThemActionPerformed

    private void jTextMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaSachActionPerformed

    private void jTableKQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKQMouseClicked
        int row = jTableKQ.getSelectedRow();
        if (row >= 0) {
            jTextMaSach.setText(jTableKQ.getValueAt(row, 0).toString());
            jTextTenSach.setText(jTableKQ.getValueAt(row, 1).toString());
            jTextTG.setText(jTableKQ.getValueAt(row, 2).toString());
            jTextNXB.setText(jTableKQ.getValueAt(row, 3).toString());
            jTextGia.setText(jTableKQ.getValueAt(row, 4).toString());

            jTextMaSach.setEditable(false); // KHÔNG ĐƯỢC PHÉP sửa mã sách
        }
    }//GEN-LAST:event_jTableKQMouseClicked

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXoaActionPerformed
        String ma = jTextMaSach.getText();
    if (ma.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sách cần xóa!");
        return;
    }
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        if (danhSach.xoaSach(ma)) { // Gọi hàm xóa từ lớp DSSach của bạn
            loadTable(); // Hàm cập nhật lại bảng đã viết ở câu trước
            clearFields(); // Hàm xóa rỗng các ô nhập
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
        }
    }
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSuaActionPerformed
       try {
        String ma = jTextMaSach.getText();
        double gia = Double.parseDouble(jTextGia.getText());
        Sach s = new Sach(ma, jTextTenSach.getText(), jTextTG.getText(), jTextNXB.getText(), gia);
        
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Xác nhận sửa?") == 0) {
            if (danhSach.capNhat(ma, s)) { loadTable(); clearFields(); }
        }
      } catch (Exception e) { javax.swing.JOptionPane.showMessageDialog(this, "Lỗi dữ liệu!"); }
    }//GEN-LAST:event_jBtnSuaActionPerformed

    private void jBtnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLuuActionPerformed
        try (java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(new java.io.FileOutputStream("sach.dat"))) {
        oos.writeObject(danhSach.getDs());
        javax.swing.JOptionPane.showMessageDialog(this, "Đã lưu vào file!");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi lưu file: " + e.getMessage());
    }
    }//GEN-LAST:event_jBtnLuuActionPerformed

    private void jBtnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTimActionPerformed
        String ma = jTextMaSach.getText();
    if (ma.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách để tìm!");
        return;
    }
    Sach s = danhSach.timSach(ma);
    if (s != null) {
        jTextTenSach.setText(s.getTenSach());
        jTextTG.setText(s.getTacGia());
        jTextNXB.setText(s.getNhaXuatBan());
        jTextGia.setText(String.valueOf(s.getGia()));
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy sách!");
    }
    }//GEN-LAST:event_jBtnTimActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThoatActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Thoát", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
        System.exit(0);
      }
    }//GEN-LAST:event_jBtnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(() -> {
        new Cau4().setVisible(true); // Thêm .setVisible(true) vào đây
       });
    }
    
    private void loadTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableKQ.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ
    for (Sach s : danhSach.getDs()) {
        model.addRow(new Object[]{s.getMaSach(), s.getTenSach(), s.getTacGia(), s.getNhaXuatBan(), s.getGia()});
       }
    }
    private void clearFields() {
        jTextMaSach.setText("");
        jTextTenSach.setText("");
        jTextTG.setText("");
        jTextNXB.setText("");
        jTextGia.setText("");
        jTextMaSach.setEditable(true); // Cho phép nhập mã mới cho lần thêm tiếp theo
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnLuu;
    private javax.swing.JButton jBtnSua;
    private javax.swing.JButton jBtnThem;
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JButton jBtnTim;
    private javax.swing.JButton jBtnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbGia;
    private javax.swing.JLabel jLbMaSach;
    private javax.swing.JLabel jLbNXB;
    private javax.swing.JLabel jLbTG;
    private javax.swing.JLabel jLbTenSach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKQ;
    private javax.swing.JTextField jTextGia;
    private javax.swing.JTextField jTextMaSach;
    private javax.swing.JTextField jTextNXB;
    private javax.swing.JTextField jTextTG;
    private javax.swing.JTextField jTextTenSach;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
