/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AndyKien
 */

public class Calculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form Calculator
     */
    private long kq = 0;
    private String phepToan = "";
    public Calculator() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }
    private void tinh() {
    if (this.phepToan.equals("")) {
        this.kq = Long.parseLong(jLabel1.getText());
    } else {
        if (this.phepToan.equals("+")) this.kq += Long.parseLong(jLabel1.getText());
        if (this.phepToan.equals("-")) this.kq -= Long.parseLong(jLabel1.getText());
        if (this.phepToan.equals("*")) this.kq *= Long.parseLong(jLabel1.getText());
        if (this.phepToan.equals("/")) this.kq /= Long.parseLong(jLabel1.getText());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt7 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btChia = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btNhan = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        btTru = new javax.swing.JButton();
        btCong = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        bt7.setText("7");
        bt7.addActionListener(this::bt7ActionPerformed);

        bt9.setText("9");
        bt9.addActionListener(this::bt9ActionPerformed);

        bt8.setText("8");
        bt8.addActionListener(this::bt8ActionPerformed);

        btChia.setText("/");
        btChia.addActionListener(this::btChiaActionPerformed);

        bt4.setText("4");
        bt4.addActionListener(this::bt4ActionPerformed);

        bt5.setText("5");
        bt5.addActionListener(this::bt5ActionPerformed);

        bt6.setText("6");
        bt6.addActionListener(this::bt6ActionPerformed);

        btNhan.setText("X");
        btNhan.addActionListener(this::btNhanActionPerformed);

        bt3.setText("3");
        bt3.addActionListener(this::bt3ActionPerformed);

        bt2.setText("2");
        bt2.addActionListener(this::bt2ActionPerformed);

        bt1.setText("1");
        bt1.addActionListener(this::bt1ActionPerformed);

        btTru.setText("-");
        btTru.addActionListener(this::btTruActionPerformed);

        btCong.setText("+");
        btCong.addActionListener(this::btCongActionPerformed);

        btHuy.setText("C");
        btHuy.addActionListener(this::btHuyActionPerformed);

        bt0.setText("0");
        bt0.addActionListener(this::bt0ActionPerformed);

        btBang.setText("=");
        btBang.addActionListener(this::btBangActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btTru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btChia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7)
                    .addComponent(bt9)
                    .addComponent(bt8)
                    .addComponent(btChia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt6)
                    .addComponent(bt5)
                    .addComponent(btNhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt3)
                    .addComponent(bt2)
                    .addComponent(btTru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHuy)
                    .addComponent(btBang)
                    .addComponent(bt0)
                    .addComponent(btCong))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt8.getText());
        }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt5.getText());
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt2.getText());
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt0.getText());
        }
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt9.getText());
        }
    }//GEN-LAST:event_bt9ActionPerformed

    private void btNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanActionPerformed
        tinh();
        this.phepToan = "*";
        jLabel1.setText("0");
    }//GEN-LAST:event_btNhanActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt1.getText());
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt7.getText());
        }
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt6.getText());
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt3.getText());
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        String gtri = this.jLabel1.getText();
        if (gtri.length() < 10) {
            if (gtri.equals("0")) gtri = "";
            this.jLabel1.setText(gtri + bt4.getText());
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void btChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChiaActionPerformed
        tinh();
        this.phepToan = "/";
        jLabel1.setText("0");
    }//GEN-LAST:event_btChiaActionPerformed

    private void btTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTruActionPerformed
        tinh();
        this.phepToan = "-";
        jLabel1.setText("0");
    }//GEN-LAST:event_btTruActionPerformed

    private void btCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCongActionPerformed
        tinh();
        this.phepToan = "+";
        jLabel1.setText("0");
    }//GEN-LAST:event_btCongActionPerformed

    private void btBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBangActionPerformed
        tinh();
        jLabel1.setText(String.valueOf(this.kq));
        this.kq = 0;
    }//GEN-LAST:event_btBangActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        jLabel1.setText("0");
        this.phepToan = "";
        this.kq = 0;
    }//GEN-LAST:event_btHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Chay roi");
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btBang;
    private javax.swing.JButton btChia;
    private javax.swing.JButton btCong;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btNhan;
    private javax.swing.JButton btTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
